# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.0
  - nightly

notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: nightly

script:
    - julia -e 'using Pkg; Pkg.update(); Pkg.build("LazIO"); Pkg.test("LazIO"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg; cd(Pkg.dir("LazIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg; cd(Pkg.dir("LazIO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
